name: Install

on: [push]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: get the compiler ready
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-9
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100
    
    - name: build and install library
      run: |
        cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
        sudo cmake --build build --target install
        rm -rf build

    - name: configure
      run: cmake -Htest -Bbuild -DTEST_INSTALLED_VERSION=1

    - name: build
      run: cmake --build build --config Debug -j4

    - name: test
      run: |
        cd build
        ctest --build-config Debug
