name: TestCoverage

on: [push, pull_request]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  upload_test_coverage:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: install gcc-9
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-9
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100
        sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-9 100
    
    - name: configure
      run: cmake -Htest/coverage -Bbuild

    - name: build
      run: cmake --build build --config Debug -j4

    - name: test
      run: |
        cd build
        ctest --build-config Debug
        cd ..
    
    - name: ready test coverage
      run: python3 test/coverage/prepare_to_upload.py argument_parser.cpp

    - name: upload test coverage
      run: curl -s https://codecov.io/bash | bash -s -- -f build/coverage/argument_parser.hpp.gcov
