name: Ubuntu

on: [push, pull_request]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: install gcc-9
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-9
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100
    
    - name: configure
      run: cmake -Htest -Bbuild

    - name: build_debug
      run: cmake --build build --config Debug -j4

    - name: test_debug
      run: |
        cd build
        ctest --build-config Debug --progress

    - name: build_release
      run: cmake --build build --config Release -j4

    - name: test_release
      run: |
        cd build
        ctest --build-config Release --progress
