name: Windows

on: [push, pull_request]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  test:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: configure
      run: cmake -Htest -Bbuild

    - name: build_debug
      run: cmake --build build --config Debug -j4

    - name: test_debug
      run: |
        cd build
        ctest --build-config Debug --progress
        cd ..
        rm build

    - name: build_release
      run: cmake --build build --config Release -j4

    - name: test_release
      run: |
        cd build
        ctest --build-config Release --progress
        cd ..
        rm build
